### ISSUE TITLE
Cannot enter username

### ISSUE THREAD

**Issue by MarshallJpn** [AzeemIdrisi/InstaLoaderApp#2] opened 2023-10-01 16:15 UTC
The textbox to enter the username is not loading, basically making the app get stuck on this screen.
![Screenshot_2023-10-01-10-13-54-580_com alphacorp instaloader-edit](https://github.com/AzeemIdrisi/InstaLoaderApp/assets/111346892/1487ab70-b43c-4bc4-92ee-f06475b759ec)

**Comment by AzeemIdrisi** [comment] 2023-10-01 16:19
Hey there! Please use a different phone until the problem is fixed.

**Comment by oyinlola007** [comment] 2023-10-03 00:20
Hi, can I take on this issue, can you assign it to me?

**Comment by AzeemIdrisi** [comment] 2023-10-03 02:15
@oyinlola007 You are now assigned to work on this, Please explain the steps to reproduce this problem and it's solution while submitting a pull request.

**Comment by AzeemIdrisi** [comment] 2023-10-06 17:31
Hi @MarshallJpn, There is a new release v1.2, Please install it and confirm if the issue persist.

**Comment by MarshallJpn** [comment] 2023-10-20 21:11
Late reply, but working on v4, thanks

![Screenshot_2023-10-20-15-10-25-111_com alphacorp instaloader-edit](https://github.com/AzeemIdrisi/InstaLoaderApp/assets/111346892/65b5acf7-7d00-498a-aafc-170942725d05)

**Closed** 2023-10-21 05:35 UTC
Labels: good first issue, hacktoberfest
